const key='__SESSION_KEY__',el=id=>document.getElementById(id);
let mediaEpoch=0;let config={},catalog=null,plan=null,context=null,busy=false,galleryPage=0,rowIndex=0,replaceMode=false,viewItem=null,objects=[];
const fields=['project','footage','audio','srt','subject','language','model','device','planner','groq_model','srt_mode','shot','background','image_count','image_provider','script','voice_url','voice_exe','voice_id','voice_speed','pause_keep','silence_min','silence_db','stock_count'];
function cfg(){return {...config,...Object.fromEntries(fields.map(k=>[k,['shot','image_count','voice_speed','pause_keep','silence_min','silence_db','stock_count'].includes(k)?Number(el(k).value):el(k).value])),text_overlays:el('text_overlays').checked,precut_project:el('precut_project').checked,precut_footage:el('precut_footage').checked}}
function status(t){el('status').textContent=t}
async function api(path,data){const r=await fetch(path,{method:data?'POST':'GET',headers:{'X-MontaVideo-Key':key,'Content-Type':'application/json'},body:data?JSON.stringify(data):undefined});const v=await r.json();if(!r.ok)throw Error(v.error||r.status);return v}
function lock(v){busy=v;document.querySelectorAll('button,input,select,textarea').forEach(e=>e.disabled=v);el('cancel').disabled=!v}
function step(n){document.querySelectorAll('main>section').forEach(s=>s.hidden=s.id!=='step'+n);document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',Number(b.dataset.step)===n));window.scrollTo(0,0)}
function connections(s){el('connectionsStatus').textContent=`Drift: ${s.token_saved?'token salvo neste computador':'não configurado'} · Groq: ${s.groq_saved?'chave salva':'não configurado'} · Pexels: ${s.pexels_saved?'salvo':'não configurado'} · Pixabay: ${s.pixabay_saved?'salvo':'não configurado'} · Serper: ${s.serper_saved?'salvo':'não configurado'}. ${s.warning||''}`;if(s.url)el('url').value=s.url;for(const [id,saved] of [['token',s.token_saved],['groq_key',s.groq_saved],['pexels_key',s.pexels_saved],['pixabay_key',s.pixabay_saved],['serper_key',s.serper_saved]])el(id).placeholder=saved?'✓ Salva neste computador · digite somente para substituir':'Ainda não configurada'}
function parseConnection(){const raw=el('connection').value.trim();if(!raw)return;let url='',token='';try{const o=JSON.parse(raw);function walk(x){if(!x||typeof x!=='object')return;for(const[k,v]of Object.entries(x)){if(typeof v==='string'){if(/^http:\/\/(127\.0\.0\.1|localhost|\[::1\])[:/]/.test(v))url=v;if(k.toLowerCase()==='authorization')token=v.replace(/^Bearer\s+/i,'');if(k==='token')token=v}if(typeof v==='object')walk(v)}}walk(o)}catch(_){url=raw.match(/^URL:\s*(\S+)/mi)?.[1]||'';token=raw.match(/^Token:\s*(\S+)/mi)?.[1]||''}if(!url||!token)throw Error('Cole a configuração ou o guia completo com URL e Token.');el('url').value=url;el('token').value=token}
function connectionInputs(){parseConnection();return {url:el('url').value,...Object.fromEntries(['token','groq_key','pexels_key','pixabay_key','serper_key'].map(k=>[k,el(k).value]))}}
async function saveConnections(){try{const r=await api('/credentials_save',{...connectionInputs(),config:cfg()});connections(r.connections);['connection','token','groq_key','pexels_key','pixabay_key','serper_key'].forEach(k=>el(k).value='');status('Salvo neste computador. Os campos de chave ficaram ocultos; seus arquivos e configurações permanecem preenchidos.')}catch(e){status(e.message)}}
async function testConnections(){try{act('check_connections',{...connectionInputs(),model:el('groq_model').value})}catch(e){status(e.message)}}
async function openProjectFolder(){try{const p=await choose('folder');if(p?.path){apply(await api('/open_project',{file:p.path}));await refreshProjects();status('Projeto aberto pela pasta.')}}catch(e){status(e.message)}}
async function launchCuts(){try{await saveConfig(false);const r=await api('/launch_cuts',{config:cfg()});status(r.message)}catch(e){status(e.message)}}
async function listenAudio(path){try{path=path||config.audio;if(!path)throw Error('Gere ou escolha um áudio primeiro.');const url=await blob('/audio_preview',{config:cfg(),path});el('audioPlayer').src=url;el('audioInfo').textContent=path;el('audioPlayer').play().catch(()=>{})}catch(e){status(e.message)}}
async function choose(kind){if(busy)return;lock(true);el('cancel').disabled=true;status('Escolha na janela do Windows ou cancele.');try{return await api('/pick',{kind})}finally{lock(false)}}
async function pick(id,kind){try{const r=await choose(kind);if(r?.path){el(id).value=r.path;if(id==='audio'){config.audio_original=r.path;config.audio_sample='';el('srt').value=''}invalidate();await saveConfig(false);status('Arquivo ou pasta escolhido.')}}catch(e){status(e.message)}}
function invalidate(){context=null;catalog=null;plan=null;renderAll()}
async function newProject(){try{const p=await choose('folder');if(!p?.path)return;apply(await api('/new_project',{parent:p.path,name:el('newName').value}));status('Projeto criado com pastas separadas. Escolha suas fontes e narração.');await refreshProjects()}catch(e){status(e.message)}}
async function openProject(){try{const f=el('projects').value;if(!f)throw Error('Escolha um projeto salvo.');apply(await api('/open_project',{file:f}));status('Projeto aberto. Nenhuma outra montagem foi carregada.')}catch(e){status(e.message)}}
function apply(r){if(r.config){config=r.config;fields.forEach(k=>{if(config[k]!==undefined){if(k==='voice_id'&&config[k]&&!Array.from(el(k).options).some(o=>o.value===config[k]))el(k).add(new Option('Voz salva',config[k]));el(k).value=config[k]}});el('precut_project').checked=!!config.precut_project;el('precut_footage').checked=!!config.precut_footage;el('text_overlays').checked=config.text_overlays!==false;el('projectTitle').textContent=config.project_name||'Nenhum projeto aberto'}for(const k of ['catalog','plan','context'])if(Object.prototype.hasOwnProperty.call(r,k)){if(k==='catalog')catalog=r[k];if(k==='plan')plan=r[k];if(k==='context'){context=r[k];if(context)el('queries').value=(context.queries||[]).join('\n')}}if(r.voices){voiceRows=r.voices;renderVoices()}if(r.audio_path)listenAudio(r.audio_path);if(r.connections)connections(r.connections);if(r.image_report)el('imageReport').textContent=`${r.image_report.downloaded} arquivos baixados em ${r.image_report.folder}. ${(r.image_report.warnings||[]).join(' ')}`;renderAll()}
async function saveConfig(show=true){if(!config.project_root){if(show)status('Crie um projeto primeiro.');return}const r=await api('/config',{config:cfg()});config=r.config;if(show)status('Projeto salvo.')}
async function confirmContext(){try{const r=await api('/confirm_context',{config:cfg()});apply(r);status(r.message);step(2)}catch(e){status(e.message)}}
async function act(action,extra={}){if(busy)return;try{lock(true);lastReadyAudio='';await api('/'+action,{config:cfg(),plan,...extra});poll()}catch(e){lock(false);status(e.message)}}
async function poll(){try{const s=await api('/state');status(s.message);if(s.audio_ready&&s.audio_ready.path!==lastReadyAudio){lastReadyAudio=s.audio_ready.path;config={...config,...s.audio_ready.config};el('audio').value=config.audio;listenAudio(lastReadyAudio)}el('logs').textContent=s.logs.join('\n');if(s.percent===null)el('progress').removeAttribute('value');else el('progress').value=s.percent;if(s.busy){setTimeout(poll,700);return}lock(false);if(s.result)apply(s.result);if(s.error)status(s.error)}catch(e){lock(false);status(e.message)}}
async function cancelJob(){try{await api('/cancel',{});status('Cancelando… Aguarde a tarefa encerrar.')}catch(e){status(e.message)}}
function renderAll(){el('contextBox').textContent=context?`${context.summary}\nPessoas: ${(context.people||[]).join(', ')||'nenhuma identificada'}. ${context.method} ${context.confirmed?'Contexto confirmado.':''}`:'Analise o roteiro para identificar país, pessoas e assunto.';const box=el('materialStats');box.replaceChildren();if(catalog){const summary=catalog.summary||{};for(const[k,title]of [['project_scenes','Cenas do projeto'],['broll_scenes','Cenas de B-roll'],['excluded','Fora do contexto']]){const d=document.createElement('div');d.className='stat';const b=document.createElement('b');b.textContent=summary[k]||0;const s=document.createElement('span');s.textContent=title;d.append(b,s);box.append(d)}}const select=el('background'),prev=select.value||config.background||'';select.replaceChildren(new Option('Escuro padrão',''));(catalog?.items||[]).filter(i=>i.role==='background').forEach(i=>select.add(new Option(base(i.path),i.path)));select.value=prev;renderSummary()}
function renderSummary(){el('planSummary').textContent=plan?`${plan.rows.length} trechos · ${(plan.duration/60).toFixed(1)} minutos · ${plan.rows.filter(r=>!r.path).length} sem mídia · ${plan.rows.filter(r=>r.approved).length} conferidos. ${Object.keys(plan.source_usage||{}).length} arquivos de origem utilizados.`:'Nenhuma montagem neste projeto.'}
function base(p){return (p||'').split(/[\\/]/).pop()}
async function openFolder(folder){try{const r=await api('/open_output',{config:cfg(),folder});status(r.message)}catch(e){status(e.message)}}
async function google(){try{await api('/search',{query:el('queries').value.split('\n')[0]||el('subject').value})}catch(e){status(e.message)}}
async function importImages(is_ai,folder){try{const p=await choose(folder?'folder':'media');if(p?.path)act('import_images',{path:p.path,is_ai})}catch(e){status(e.message)}}
function openGallery(kind,replace=false){if(!catalog){status('Prepare o material na etapa 2.');return}replaceMode=replace;galleryPage=0;el('galleryKind').value=kind;el('gallerySearch').value='';el('galleryTitle').textContent=replace?'Escolher outra cena':'Seu material preparado';el('gallery').showModal();renderGallery()}
function closeGallery(){el('gallery').close();replaceMode=false}
async function blob(path,data){const r=await fetch(path,{method:'POST',headers:{'X-MontaVideo-Key':key,'Content-Type':'application/json'},body:JSON.stringify(data)});if(!r.ok)throw Error((await r.json()).error);const url=URL.createObjectURL(await r.blob());objects.push(url);return url}
let galleryEpoch=0;
function renderGallery(){const epoch=++galleryEpoch,kind=el('galleryKind').value,search=el('gallerySearch').value.toLowerCase();let items=(catalog?.items||[]).filter(i=>kind==='excluded'?i.context_allowed===false:kind==='images'?i.kind==='image'&&i.role!=='background':i.kind==='video'&&(i.origin===kind||(kind==='footage'&&i.origin==='stock'))&&i.precut&&i.context_allowed!==false).filter(i=>(i.path+' '+(i.original_source||'')).toLowerCase().includes(search));const pages=Math.max(1,Math.ceil(items.length/9));galleryPage=Math.min(galleryPage,pages-1);el('galleryPages').textContent=`${galleryPage+1}/${pages} · ${items.length} arquivos`;const root=el('galleryCards');root.replaceChildren();items.slice(galleryPage*9,galleryPage*9+9).forEach(i=>{const card=document.createElement('button');card.className='tile'+(i.reviewed?' selected':'');const img=document.createElement('img');img.alt='Prévia de '+base(i.path);const info=document.createElement('div');info.className='info';const b=document.createElement('b');b.textContent=base(i.path);const small=document.createElement('small');small.textContent=i.kind==='video'?`${i.origin==='stock'?'B-roll baixado':'Cortada'} · ${Number(i.duration).toFixed(1)}s · ${base(i.original_source||i.path)}`:`${i.origin==='ai_local'?'Imagem IA local':'Foto / imagem'} · ${i.reviewed?'aprovada':'conferir'}`;info.append(b,small);card.append(img,info);card.onclick=()=>view(i);root.append(card);blob('/thumb',{config:cfg(),path:i.path,at:0}).then(url=>{if(epoch===galleryEpoch)img.src=url;else URL.revokeObjectURL(url)}).catch(()=>img.alt='Prévia indisponível; clique para tentar')})}
async function view(item){viewItem=item;el('viewerTitle').textContent=base(item.path);el('viewerInfo').textContent=`${item.context_reason||''}\nOrigem: ${item.original_source||item.path}\n${item.source?.url||item.source?.page||''}`;const link=item.source?.page||item.source?.url||'';el('viewerSource').hidden=!/^https?:/.test(link);el('viewerSource').href=/^https?:/.test(link)?link:'#';el('viewerInfo').textContent+='\n'+(item.source?.author||item.source?.artist||'')+' · '+(item.source?.provider||'')+'\n'+(item.source?.license||'');el('useImageLabel').hidden=item.kind!=='image';el('useImage').checked=!!item.reviewed;el('useImage').onchange=()=>{item.reviewed=el('useImage').checked};el('replaceButton').hidden=!replaceMode||item.context_allowed===false;el('viewer').showModal();await media(item.path,0,Math.min(item.duration||5,15),'video','photo')}
async function media(path,start,duration,videoId,photoId){const epoch=++mediaEpoch,v=el(videoId),img=el(photoId);v.pause();v.hidden=true;img.hidden=true;const item=catalog?.items.find(i=>i.path===path);if(!item){status('Trecho sem mídia. Escolha uma cena.');return}try{const isVideo=item.kind==='video';const url=await blob(isVideo?'/preview':'/thumb',{config:cfg(),path,at:start,duration});if(epoch!==mediaEpoch){URL.revokeObjectURL(url);return}if(isVideo){v.src=url;v.hidden=false;v.play().catch(()=>{})}else{img.src=url;img.hidden=false}}catch(e){status(e.message)}}
function closeViewer(){mediaEpoch++;el('video').pause();el('viewer').close();renderGallery()}
function replaceScene(){if(!plan||!viewItem)return;const r=plan.rows[rowIndex];if(viewItem.kind==='video'&&viewItem.duration<r.duration){status('Esta cena é menor que o trecho. Escolha uma cena mais longa.');return}r.path=viewItem.path;r.source_in=0;r.approved=false;r.zoom=viewItem.kind==='image';delete r.source_limit;closeViewer();closeGallery();showRow(rowIndex)}
async function saveImageChoices(){await act('review_images',{reviewed:(catalog?.items||[]).filter(i=>i.reviewed).map(i=>i.path)})}
function openReview(){if(!plan){status('Gere a base do vídeo primeiro.');return}el('review').showModal();showRow(0)}
function showRow(index){if(!plan)return;rowIndex=Math.max(0,Math.min(plan.rows.length-1,index));const r=plan.rows[rowIndex];el('rowTitle').textContent=`Trecho ${rowIndex+1}/${plan.rows.length} · ${r.at.toFixed(1)}s · duração ${r.duration.toFixed(1)}s`;el('rowText').textContent=r.text;el('rowSource').textContent=base(r.path)||'Sem mídia';el('sourceIn').value=r.source_in;el('rowApproved').checked=!!r.approved;el('rowZoom').value=r.zoom?r.zoom_direction||'in':'none';el('rowReason').textContent=r.reason;el('rowOverlay').value=r.overlay||'';playRow()}
function playRow(){const r=plan.rows[rowIndex];return media(r.path,r.source_in,r.duration,'reviewVideo','reviewPhoto')}
function editEntry(){const r=plan.rows[rowIndex];r.source_in=Number(el('sourceIn').value);r.approved=false;delete r.source_limit;el('rowApproved').checked=false;renderSummary()}
function setZoom(){const r=plan.rows[rowIndex],v=el('rowZoom').value;r.zoom=v!=='none';r.zoom_direction=v==='none'?'in':v}
function approveAll(){if(confirm('Você conferiu os trechos e quer confirmar todos os que têm mídia?')){plan.rows.forEach(r=>{if(r.path)r.approved=true});showRow(rowIndex);renderSummary()}}
function closeReview(){mediaEpoch++;el('reviewVideo').pause();el('review').close();act('save')}
async function refreshProjects(){const r=await api('/load');const select=el('projects');select.replaceChildren(new Option('Escolha um projeto',''));(r.projects||[]).forEach(p=>select.add(new Option(p.name,p.file)));return r}
for(const name of ['precut_project','precut_footage'])el(name).addEventListener('change',()=>{catalog=null;plan=null;renderAll();saveConfig(false).catch(e=>status(e.message))});
for(const name of ['project','footage','audio','srt','subject'])el(name).addEventListener('change',()=>{if(name==='audio'){config.audio_original=el('audio').value;config.audio_sample='';el('srt').value=''}invalidate();saveConfig(false).catch(e=>status(e.message))});
(async()=>{try{const r=await refreshProjects();apply({config:r.config});connections(r.connections);renderAll()}catch(e){status(e.message)}})();

for(const name of fields.filter(k=>!['project','footage','audio','srt','subject'].includes(k)))el(name).addEventListener('change',()=>saveConfig(false).catch(e=>status(e.message)));

let voiceRows=[],lastReadyAudio='';
function renderVoices(){const select=el('voice_id'),previous=select.value||config.voice_id||'',q=el('voiceSearch').value.toLowerCase();select.replaceChildren(new Option('Escolha uma voz · obrigatório',''));for(const group of ['Perfis salvos','Galeria']){const g=document.createElement('optgroup');g.label=group;voiceRows.filter(v=>v.group===group&&(v.id===previous||(v.name+' '+v.description).toLowerCase().includes(q))).forEach(v=>g.append(new Option(v.name,v.id)));select.append(g)}if(previous&&!Array.from(select.options).some(o=>o.value===previous))select.add(new Option('Voz salva · recarregue para verificar',previous));select.value=previous;voiceDetail()}
function voiceDetail(){const v=voiceRows.find(v=>v.id===el('voice_id').value);el('voiceDetails').textContent=v?`${v.name} · ${v.group}. ${v.description||''}`:'Selecione uma voz antes de gerar. Não existe seleção aleatória.'}
el('voice_id').addEventListener('change',voiceDetail);
